### PR TITLE
Add possibilty to open popup in VNC (or with Mouse) by righclick

### PR DESCRIPTION
**Pull request by ski7777**
This adds a better usability to VNC

### CODE REVIEW

**Comment by ski7777** [comment]
Why do you just close this?

**Comment by harbaum** [comment]
There's a reason why I am doing this in my personal fork. You can in turn fork that and do whatever you want in your own fork but i don't see a reason why you should mess with my personal work in progress.

**Comment by ski7777** [comment]
So
I will try it again after your solution is finished and merged to the main repository.

**Comment by harbaum** [comment]
I don't plan to merge this with the main repository.

**Comment by harbaum** [comment]
Just to clarify: This contains the finger scrolling which the majority didn't like. So i won't force this into the main repository.

**Pull request closed without merging**
